MAJOUR IMPROVEMENTS
jessm16/CS1200 pull request #3
Opened 2017-11-17 18:59 UTC by khalilhaji

2017-11-17 19:03 UTC, khalilhaji commented
Richard Stallman's Personal Site

Political Articles | Political Notes | Travel Experiences | Travel Photos | Fiction | Books | Sayings | Personal Ad | Humor | Non-Political Articles | RMS personal FAQ | GPG Key | Scientific Links | Airlines | Humorous Bio | Comics | Empire of the Megacorporations | There Ought to Be a Law | Media/Press/Bio | Links | Archive | Glossary | Anti-Glossary | Thanks |

Site search: 
  go advanced
Send comments/questions about the search engine to: rms at gnu dot org


What's bad about: Airbnb | Amazon | Amtrak | Ancestry | Apple | Ebooks | Eventbrite | Evernote | Facebook | Google | Intel | LinkedIn | Lyft | Meetup | Microsoft | Netflix | Pay Toilets | Skype | Spotify | Twitter | Uber |
RSS site feed for the most recent political notes and new material.

This is the personal web site of Richard Stallman.
The views expressed here are my personal views, not those of the Free Software Foundation or the GNU Project.
If you want to send me GPG-encrypted mail, do not trust key servers! Some of them have phony keys under my name and email address, made by someone else as a trick. See gpg.html for my real key.

Support the US Green Party.

Support the Citizens' Climate Lobby.

Please donate to the Free Software Foundation to support its work for your freedom.

Link Policy

Toggle Dark Theme

The largest part of the site is the political notes, and they are typically updated every day.

I'm looking for people to…

search for things such as people's email addresses or other contact coordinates.
(in India) make and sell buttons that say, "DON'T BE TRACKED  PAY CASH", in English and/or a local language, to resist the campaign against cash. Talk with a local company that makes buttons, buy a batch of 50 to 500 buttons for a quantity price, then sell them for 2 or 3 times that price.
post videos of my talks on audio-video.gnu.org.
write a recipe for how to connect to the WiFi in a New York City subway station without running its nonfree Javascript code. The recipe could include a free Javascript program I could run, or it could consist of instructions for what I would type into IceCat (our variant of Firefox). It doesn't have't be super convenient, it just has to work.
help maintain and operate savannah.gnu.org.
help web sites put free licenses on their Javascript code.
write site-specific Firefox extensions or local scripts to operate specific web sites.
help webmasters of various sites (not related to me or GNU) make simple but substantial changes in their web sites — for instance, to use the GNU Project's recommended terminology.
experiment to find good ways to attach fruits to a Grav-mass tree.
Please email rms at the gnu site if you want to volunteer for any of those activities. For the Grav-mass decorations, please write if you come up with a good way.

Civil Liberties Minute:

[America Means Civil Liberties / Patriotism Means Protecting 
             Them / www.aclu.org/safefree ]
graphic by Susan Henson
Americans, you may wish to copy this icon to your own page, as a way of showing what patriotism means to you.

Urgent action items

Everyone: call on REI to give its staff a raise to $15 an hour.

US citizens: oppose the nomination of a saboteur to head the Council on Environmental Quality.

US citizens: call on Congress to let veterans have medical marijuana.

US citizens: call on your congresscritter and senators to co-sponsor S. 1539, which would ban those convicted of domestic violence from buying or owning guns.

US citizens: call on Congress to renew the Rohrabacher-Blumenauer amendment whereby the US government does not interfere with medical marijuana legalized by states.

US citizens: phone certain Republican congresscritters to oppose even one penny of tax cuts for rich people and rich corporations.

US citizens: if your congresscritter is a Democrat, call on per to read the Democratic Party autopsy and respond to it.

You can sign this without running the page's nonfree Javascript code using the Salsalabs workaround.

US citizens: call on US bank regulators to cut off Wells Fargo.

US citizens: phone your congresscritter at 1-866-665-4470 and call for removing the clause in the tax bill that declares fetuses to be persons (and abortion to be murder).

Recording of Guantanamero

Listen to the recording of Guantanamero, a protest song written in Spanish. The recording is in Ogg Vorbis format. To install an Ogg Vorbis player, see the FSF's Ogg Players page.
There Ought to Be a Law

We need a law requiring the immigration agency to publish all its data about a particular person's interrogation or exclusion, if that person publicly asks. We must not allow the agency to hide its refusal to explain itself to the victim behind a facade of concern for the victim's own privacy.
To treat a payment to a foreign company as a tax-deductable business expense, that company should have to disclose its true owners, and whatever other information is needed to prevent tax dodging.
Fine government contractors for hiring ex-officials.
Businesses should be heavily fined if they use subcontracted workers to do any given kind of work for more than 120 hours in each of 4 successive months. If a business steadily needs that much work of a given kind, it should hire regular staff to do the work and give them regular benefits.
More items where there ought to be a law.
Quotes

Here are some quotations that I particularly like.

Most recent Political Notes and News Items

(RSS Feed)


See the current pol-notes page for more.

(You may need to scroll down for more text if there is blank space in this column.)

 Anuran Bevan [More Cartoons]


Not f'd. You won't find us on Facebook
Copy this button (courtesy of R.Siddharth) to express your rejection of Facebook.

Support the Green Party


Republican Election Rigging Tactics


Evoting


The Olympics


Why everyone has a reason to fear massive surveillance


Churchandstate.org.uk

E-books

Non-oppressive Commercial E-books

Don't use Facebook

Facebook's face recognition demonstrates a threat to everyone's privacy. I therefore ask people not to put photos of me on Facebook; you can do likewise.

Of course, Facebook is bad for many other reasons as well.

Boycott Harry Potter Books, Movies, etc.


Internet Music EULAS


Business Supremacy Treaties


No national identity cards

I'd like to make a list of countries that do not require a national identity card, and have no plans to adopt one. If you live in or have confirmed knowledge of such a country, please send email to rms at gnu.org.

Here's my list of countries with no national ID cards and no plans for one: Australia, Canada, New Zealand, UK, the Philippines. Australia's previous government tried to institute national ID cards, but the Labor government dropped the plan.

India has mostly finished imposing a national biometric ID number in a grand act of oppression.

Switzerland has national ID cards which are optional, but they or some other government ID card are needed for some purposes.

Iceland doesn't have ID cards as such, but they have ID numbers that citizens are forced to use frequently. For example, the national ID number is often required to rent a video or use a gym.

Denmark issues non-photo ID cards with a "person number", and many services use this card to identify people.

Norway will impose a national biometric ID card.

Ireland - national ID card by stealth.

ACLU: the five dangers of national ID cards.

Wikipedia has a list of identity card policies by country.

Borders

Stay away from certain countries because of their bad immigration policies.

Flight connections

Avoid flight connections in these airports because of their treatment of passengers.

The Lifelong Activist

People often ask how I manage to continue devoting myself to progressive activism (such as the free software movement) for years without burning out. The best way I can answer is by recommending a book, The Lifelong Activist by Hillary Rettig.

I disagree with  [...]

2017-11-17 19:10 UTC, kylesferrazza requested changes
remove bee movie script pls

2017-11-17 19:11 UTC, edward-shen requested changes
Terrible. undo everything pls

2020-07-24 19:36 UTC, closed without merging

2026-11-06 19:18 UTC, dagerfernando19-lab commented
Metrolist Playback Error Report
================================
Time: 1970-01-02T22:47:08.068Z
App version: 13.7.0 (153)
Architecture: universal
Android: 14 (API 34)
Device: OPPO CPH2387

Media
-----
Title: UNA NOCHE DE LOCURA
Artists: Blessd, Sebastian Ledher, Tayson Kryss, Joseph Ren
ID: TfD2jtYLlMc
Link: https://music.youtube.com/watch?v=TfD2jtYLlMc
Stream client: WEB_REMIX

Error
-----
Code: IO_UNSPECIFIED (2000)
[0] androidx.media3.exoplayer.ExoPlaybackException: Source error
[1] androidx.media3.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected PlaybackException: Error desconocido
[2] androidx.media3.common.PlaybackException: Error desconocido
[3] androidx.compose.runtime.snapshots.SnapshotApplyConflictException: Player request for WEB_CREATOR exceeded 8000ms
[4] kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 8000 ms

Stack trace
-----------
androidx.media3.exoplayer.ExoPlaybackException: Source error
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(r8-map-id-5938931b1319154e8f473214fc5d5f6e92c71a729872ba9a4bc6a2026f181b2f:17)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(r8-map-id-5938931b1319154e8f473214fc5d5f6e92c71a729872ba9a4bc6a2026f181b2f:457)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: androidx.media3.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected PlaybackException: Error desconocido
	at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(r8-map-id-5938931b1319154e8f473214fc5d5f6e92c71a729872ba9a4bc6a2026f181b2f:135)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1100)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:1571)
Caused by: androidx.media3.common.PlaybackException: Error desconocido
	at androidx.media3.session.MediaSessionStub$$ExternalSyntheticLambda81.resolveDataSpec(r8-map-id-5938931b1319154e8f473214fc5d5f6e92c71a729872ba9a4bc6a2026f181b2f:790)
	at androidx.media3.datasource.ResolvingDataSource.open(r8-map-id-5938931b1319154e8f473214fc5d5f6e92c71a729872ba9a4bc6a2026f181b2f:3)
	at androidx.media3.datasource.StatsDataSource.open(r8-map-id-5938931b1319154e8f473214fc5d5f6e92c71a729872ba9a4bc6a2026f181b2f:11)
	at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(r8-map-id-5938931b1319154e8f473214fc5d5f6e92c71a729872ba9a4bc6a2026f181b2f:28)
	at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(r8-map-id-5938931b1319154e8f473214fc5d5f6e92c71a729872ba9a4bc6a2026f181b2f:35)
	... 3 more
Caused by: androidx.compose.runtime.snapshots.SnapshotApplyConflictException: Player request for WEB_CREATOR exceeded 8000ms
	at com.metrolist.innertubex.extraction.PlayerClientDirector.requestPlayer(r8-map-id-5938931b1319154e8f473214fc5d5f6e92c71a729872ba9a4bc6a2026f181b2f:167)
	at com.metrolist.innertubex.extraction.PlayerClientDirector$requestPlayer$1.invokeSuspend(r8-map-id-5938931b1319154e8f473214fc5d5f6e92c71a729872ba9a4bc6a2026f181b2f:20)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(r8-map-id-5938931b1319154e8f473214fc5d5f6e92c71a729872ba9a4bc6a2026f181b2f:8)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(r8-map-id-5938931b1319154e8f473214fc5d5f6e92c71a729872ba9a4bc6a2026f181b2f:7)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(r8-map-id-5938931b1319154e8f473214fc5d5f6e92c71a729872ba9a4bc6a2026f181b2f:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(r8-map-id-5938931b1319154e8f473214fc5d5f6e92c71a729872ba9a4bc6a2026f181b2f:33)
	at kotlinx.coroutines.DispatchedTask.run(r8-map-id-5938931b1319154e8f473214fc5d5f6e92c71a729872ba9a4bc6a2026f181b2f:106)
	at androidx.core.app.ActivityRecreator$1.run(r8-map-id-5938931b1319154e8f473214fc5d5f6e92c71a729872ba9a4bc6a2026f181b2f:11)
	at kotlinx.coroutines.scheduling.TaskImpl.run(r8-map-id-5938931b1319154e8f473214fc5d5f6e92c71a729872ba9a4bc6a2026f181b2f:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(r8-map-id-5938931b1319154e8f473214fc5d5f6e92c71a729872ba9a4bc6a2026f181b2f:88)
Caused by: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 8000 ms
	at kotlinx.coroutines.TimeoutCoroutine.run(r8-map-id-5938931b1319154e8f473214fc5d5f6e92c71a729872ba9a4bc6a2026f181b2f:84)
	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(r8-map-id-5938931b1319154e8f473214fc5d5f6e92c71a729872ba9a4bc6a2026f181b2f:3)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(r8-map-id-5938931b1319154e8f473214fc5d5f6e92c71a729872ba9a4bc6a2026f181b2f:101)
	at kotlinx.coroutines.DefaultExecutor.run(r8-map-id-5938931b1319154e8f473214fc5d5f6e92c71a729872ba9a4bc6a2026f181b2f:57)
	at java.lang.Thread.run(Thread.java:1571)


Me pasa en todas las canciones este error